
model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "../../shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "forward-cycle-EDSR"
  manual_seed: 1265

EDSR:
 rgb_range : 255
 n_colors : 3
 n_feats : 256 #initially 256
 n_resblocks : 32
 res_scale : 0.1
 kernel_size : 3
 scale : 4

Gtwo:
  c : 64  #initially 256
  batchnorm : True
  kernels : [3,3]

