

logging_params:
  log : True
  log_interval : 50
  image_log : 250 # Save images every 100 logs in an epoch
  #image log: must be multiple of log_interval
  save_dir: "logs/SpecNorm/"
  name: "forward-cycle-EDSR"


hyperparams:
  gpus: 1
  epochs : 500
  TotalVariation_Weight: 0.01
  Identity_Weight : 100000
  Content_Weight : 10
  lambda_weight : 50 #cycle consistency loss

model_params:
  name: 'Forward-cycle-EDSR'
  manual_seed: 955
  loss: ls  # least square, other variants: Wasserstein
#  in_channels: 3
#  latent_dim: 128

exp_params:
#  dataset: celeba
  data_path: "/tmp/Datasets/"
  #If you want to try with different models
  lr_datapath : "DIV2k"
  hr_datapath :  "celeba/img_align_celeba"

  hr_imageSize: 64
  lr_imageSize: 16
  normalisation: InstanceNorm2d
  batch_size: 64 # Better to have a square number
  test_split : 20  # means 80% training, and 20% testing
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  num_workers : 0
  shuffle : True # Shuffle the dataset


EDSR:
 rgb_range : 255
 n_colors : 3
 n_feats : 256 #initially 256
 n_resblocks : 32
 res_scale : 0.1
 kernel_size : 3
 scale : 4
 save_dir: "/tmp/Datasets/DIV2k/CycleEDSR"

Gtwo:
  c : 64  #initially 256
  batchnorm : True
  kernels : [3,3]

