logging_params:
  log : True
  log_interval : 25
  image_log : 50 # Save images every 100 logs in an epoch
  #image log: must be multiple of log_interval
  save_dir: "logs/test/"
  name: "forward-cycle-EDSR"

hyperparams:
  gpus: 1
  epochs : 500
  TotalVariation_Weight: 0.0001
  Identity_Weight : 1
  Content_Weight : 0.2

  lambda_weight : 0.3 #cycle consistency loss

model_params:
  name: 'Forward-cycle-EDSR'
  manual_seed: 955
  loss: ls  # least square, other variants: Wasserstein
#  in_channels: 3
#  latent_dim: 128

exp_params:  ##EXPERIMENT PARAMS
#  dataset: celeba
  data_path: "/tmp/Datasets/"
  #If you want to try with different models
  lr_datapath : "DIV2k/no_variance"
#  hr_datapath :  "celeba/img_align_celeba"
  hr_datapath: "3Dto2D/variance"
  FID : '/128'
  hr_imageSize: 128
  lr_imageSize: 32
  normalisation: BatchNorm2d
  batch_size: 8 # Better to have a square number and not less than 8!!!
  test_split : 10  # means 80% training, and 20% testing
  lr : 0.00001
  beta1 : 0.5
  beta2 : 0.99 # default value
  weight_decay: 0.0
  scheduler_gamma: 0.95
  num_workers : 0
  shuffle : True # Shuffle the dataset


EDSR:
 rgb_range : 255
 n_colors : 3
 n_feats : 256 #initially 256
 n_resblocks : 32
 res_scale : 0.1
 kernel_size : 3
 scale : 4
 edsr_save: "/tmp/Datasets/DIV2k/model2/EDSR" #used in edsrOnly
 save_dir: "/tmp/Datasets/DIV2k/model2/CycleEDSR"

Gtwo:
  c : 64  #initially 256
  batchnorm : True
  kernels : [3,3]

