logging:
  save_dir : "test1/"
  name: "style-transfer"
  manual_seed: 656
  save_model_interval: 10000
  image_save: 500

model:
  vgg : '/tmp/models/vgg_normalised.pth'
  save_dir: 'network/'

exp:
  max_iter : 100000
#  dataset: celeba
  data_path: "/tmp/Datasets/"
  #If you want to try with different models
  lr_datapath : "DIV2k/images"
#  hr_datapath :  "celeba/img_align_celeba"
  hr_datapath: "3Dto2D/squared/uniques"
  FID : '/128'
  hr_imageSize: 64
  lr_imageSize: 64
  batch_size: 64 # Better to have a square number and not less than 8!!!
  test_split : 10  # means 80% training, and 20% testing
  lr : 0.0001
  lr_decay : 0.00005
  num_workers : 0
  shuffle : True # Shuffle the dataset

loss:
  kld_alpha: 0.75
  rec_alpha: 1

